name: Deploy and Test MERN App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy-int:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Command
        run: npm run build

      - name: Start Command
        run: npm tart

      - name: Deploy to Render (Integration)
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_INT_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "$RENDER_SERVICE_ID", "clearCache": false}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys

  test-int:
    runs-on: ubuntu-latest
    needs: build-and-deploy-int
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Wait for deployment to complete
        run: sleep 120

      - name: Run Cypress tests
        run: npm run test
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_INT_BASE_URL }}

  build-and-deploy-pro:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Render (Production)
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_PRO_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"serviceId": "$RENDER_SERVICE_ID", "clearCache": false}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys

  test-pro:
    runs-on: ubuntu-latest
    needs: build-and-deploy-pro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Wait for deployment to complete
        run: sleep 120

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_PRO_BASE_URL }}
